# ARTISTS = ['лигалайз', 'многоточие', 'krec', 'guf', 'баста', 'каста', 'ак-47', 'каспийский груз', 'кровосток', 'the chemodan', 'смоки мо', 'рем дигга', 'миша маваши', 'd-man 55', 'грот', 'oxxxymiron', 'соня мармеладова', 'alyona alyona', 'sid', 'redo', 'ram', 'полумягкие', 'оу74', 'паша техник', 'овсянкин', 'pharaoh', 'boulevard depo', 'mnogoznaal', 'kizaru', 'лсп', 'atl', 'макс корж', 'slava marlow', 'скриптонит', 'noize mc', 'loqiemean', 'anacondaz', '25/17', 'lizer', 'джизус', 'мукка', 'lizer', 'face', 'gone.fludd', 'big baby tape', 'элджей', 'morgenshtern', 'rakhim', 'егор крид', 'тимати', 'pyrokinesis', 't-fest', 'miyagi', 'jah khalib', 'hammali & navai']
# GENRES = ['freestyle', 'regular', 'emo', 'raprock', 'cloud', 'club', 'drill', 'electronicvocal', 'grime', 'mumble', 'phonk', 'hardcore', 'horrorcore', 'underground', 'hookah', 'pop', 'gangsta', 'workout', 'classic', 'soft']

search_verbs = ('найти', 'показать', 'вывести')
search_nouns = ('похожий', 'схожий')
# похожих на многоточие, все кроме многоточия
ARTISTS = {
    'лигалайз': 'лигалайз',
    'лигалайза': 'лигалайз',
    'многоточие': 'многоточие',
    'многоточия': 'многоточие',
    'krec': 'krec',
    'крек': 'krec',
    'крека': 'krec',
    'guf': 'guf',
    'гуф': 'guf',
    'гуфа': 'guf',
    'баста': 'баста',
    'басту': 'баста',
    'каста': 'каста',
    'касту': 'каста',
    'ак-47': 'ак-47',
    'каспийский груз': 'каспийский груз',
    'каспийского груза': 'каспийский груз',
    'кровосток': 'кровосток',
    'кровостока': 'кровосток',
    'chemodan': 'the chemodan',
    'the chemodan': 'the chemodan',
    'чемодан': 'the chemodan',
    'чемодана': 'the chemodan',
    'смоки мо': 'смоки мо',
    'рем дигга': 'рем дигга',
    'рем дигги': 'рем дигга',
    'рем диггу': 'рем дигга',
    'миша маваши': 'миша маваши',
    'мишу маваши': 'миша маваши',
    'd-man 55': 'd-man 55',
    'грот': 'грот',
    'oxxxymiron': 'oxxxymiron',
    'оксимирон': 'oxxxymiron',
    'оксимирона': 'oxxxymiron',
    'соня мармеладова': 'соня мармеладова',
    'соня мармеладову': 'соня мармеладова',
    'соню мармеладову': 'соня мармеладова',
    'alyona alyona': 'alyona alyona',
    'алёна алёна': 'alyona alyona',
    'алена алена': 'alyona alyona',
    'алену алену': 'alyona alyona',
    'sid': 'sid',
    'сид': 'sid',
    'сида': 'sid',
    'redo': 'redo',
    'редо': 'redo',
    'рэдо': 'redo',
    'ram': 'ram',
    'рэм': 'ram',
    'рэма': 'ram',
    'полумягкие': 'полумягкие',
    'полумягких': 'полумягкие',
    'оу74': 'оу74',
    'паша техник': 'паша техник',
    'паши техника': 'паша техник',
    'пашу техника': 'паша техник',
    'овсянкин': 'овсянкин',
    'овсянкина': 'овсянкин',
    'pharaoh': 'pharaoh',
    'фараон': 'pharaoh',
    'фараона': 'pharaoh',
    'boulevard depo': 'boulevard depo',
    'бульвар депо': 'boulevard depo',
    'бульвара депо': 'boulevard depo',
    'mnogoznaal': 'mnogoznaal',
    'многознал': 'mnogoznaal',
    'многознала': 'mnogoznaal',
    'многознаал': 'mnogoznaal',
    'многознаала': 'mnogoznaal',
    'kizaru': 'kizaru',
    'кизару': 'kizaru',
    'лсп': 'лсп',
    'atl': 'atl',
    'атл': 'atl',
    'атла': 'atl',
    'макс корж': 'макс корж',
    'макса коржа': 'макс корж',
    'slava marlow': 'slava marlow',
    'слава мэрлоу': 'slava marlow',
    'славу мэрлоу': 'slava marlow',
    'славы мэрлоу': 'slava marlow',
    'скриптонит': 'скриптонит',
    'скриптонита': 'скриптонит',
    'noize mc': 'noize mc',
    'нойз мс': 'noize mc',
    'нойза мс': 'noize mc',
    'нойз': 'noize mc',
    'нойза': 'noize mc',
    'loqiemean': 'loqiemean',
    'локимин': 'loqiemean',
    'локимина': 'loqiemean',
    'anacondaz': 'anacondaz',
    'анакондаз': 'anacondaz',
    '25/17': '25/17',
    'lizer': 'lizer',
    'лизер': 'lizer',
    'лизера': 'lizer',
    'джизус': 'джизус',
    'джизуса': 'джизус',
    'мукк': 'мукка',
    'мукка': 'мукка',
    'мукку': 'мукка',
    'face': 'face',
    'фейс': 'face',
    'фэйс': 'face',
    'фейса': 'face',
    'фэйса': 'face',
    'gone.fludd': 'gone.fludd',
    'гон флад': 'gone.fludd',
    'гон флада': 'gone.fludd',
    'big baby tape': 'big baby tape',
    'биг бейби тейп': 'big baby tape',
    'биг бэйби тейп': 'big baby tape',
    'биг бейби тэйп': 'big baby tape',
    'биг бэйби тэйп': 'big baby tape',
    'биг бейби тейпа': 'big baby tape',
    'биг бэйби тейпа': 'big baby tape',
    'биг бейби тэйпа': 'big baby tape',
    'биг бэйби тэйпа': 'big baby tape',
    'элджей': 'элджей',
    'элджейя': 'элджей',
    'morgenshtern': 'morgenshtern',
    'моргенштерн': 'morgenshtern',
    'моргенштерна': 'morgenshtern',
    'rakhim': 'rakhim',
    'рахим': 'rakhim',
    'рахима': 'rakhim',
    'егор крид': 'егор крид',
    'егора крида': 'егор крид',
    'тимати': 'тимати',
    'pyrokinesis': 'pyrokinesis',
    'пирокинезис': 'pyrokinesis',
    'пирокинезиса': 'pyrokinesis',
    't-fest': 't-fest',
    'ти-фест': 't-fest',
    'ти-феста': 't-fest',
    'ти фест': 't-fest',
    'ти феста': 't-fest',
    'miyagi': 'miyagi',
    'мияги': 'miyagi',
    'jah khalib': 'jah khalib',
    'джа халиб': 'jah khalib',
    'джа халиба': 'jah khalib',
    'hammali & navai': 'hammali & navai',
    'хамали & наваи': 'hammali & navai',
    'хамали и наваи': 'hammali & navai',
}
GENRES = {
    'emo': 'emo',
    'эмо': 'emo',
    'raprock': 'raprock',
    'rap rock': 'raprock',
    'рэп рок': 'raprock',
    'рэп-рок': 'raprock',
    'реп рок': 'raprock',
    'реп-рок': 'raprock',
    'cloud': 'cloud',
    'клауд': 'cloud',
    'club': 'club',
    'клуб': 'club',
    'клубный': 'club',
    'drill': 'drill',
    'дрилл': 'drill',
    'electronicvocal': 'electronicvocal',
    'grime': 'grime',
    'грайм': 'grime',
    'mumble': 'mumble',
    'мамбл': 'mumble',
    'phonk': 'phonk',
    'фонк': 'phonk',
    'hardcore': 'hardcore',
    'хардкор': 'hardcore',
    'horrorcore': 'horrorcore',
    'хорроркор': 'horrorcore',
    'хороркор': 'horrorcore',
    'underground': 'underground',
    'андеграунд': 'underground',
    'hookah': 'hookah',
    'кальян': 'hookah',
    'кальянный': 'hookah',
    'pop': 'pop',
    'поп': 'pop',
    'gangsta': 'gangsta',
    'гангста': 'gangsta',
    'ганста': 'gangsta',
    'workout': 'workout',
    'воркаут': 'workout',
    'спортивный': 'workout',
    'спорт': 'workout',
}
